### PR TITLE
Avoid unused parameter warnings in do_get_mem_info

### LINKED ISSUE #1032: `unused parameter` warnings for do_get_mem_info
The stream parameter in do_get_mem_info(stream) is unused for some memory resources, for example

https://github.com/rapidsai/rmm/blob/branch-22.06/include/rmm/mr/device/managed_memory_resource.hpp#L117 

```  [[nodiscard]] std::pair<std::size_t, std::size_t> do_get_mem_info(
    cuda_stream_view stream) const override
  {
    std::size_t free_size{};
    std::size_t total_size{};
    RMM_CUDA_TRY(cudaMemGetInfo(&free_size, &total_size));
    return std::make_pair(free_size, total_size);
  }
```

This leads to compiler warnings.

### PR DESCRIPTION
**Pull request by fkallen**
closes #1032

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Review by harrism — APPROVED** [review]

**Review by rongou — APPROVED** [review]

**Comment by rongou** [comment]
ok to test

**Review by jrhemstad — APPROVED** [review]

**Comment by harrism** [comment]
ok to test

**Comment by harrism** [comment]
@fkallen can you run clang-format to fix the style failures?

**Comment by harrism** [comment]
Hmmm, that doesn't seem to have fixed it.

**Comment by harrism** [comment]
@gpucibot merge

**Comment by harrism** [comment]
@gpucibot merge

**Pull request merged**
