### PR TITLE
stop installing 'wheel' in wheel-building script

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

We're now pre-installing `wheel` in the CI images: https://github.com/rapidsai/ci-imgs/pull/215

This proposes removing a `pip install wheel` in CI here... fewer network requests = fewer random CI failures 😁 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by jameslamb** [comment]
This is ready for review. The `pre-commit.ci` job failure is a result of the testing happening in #1746

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
#1746 is fixed up and merged. This should be mergeable without the upstream though, so I’ll trigger it.

**Pull request merged**
