### PR TITLE
WIP: Use pinned memory in tobytes

### PR DESCRIPTION
**Pull request by jakirkham**
Makes use of pinned memory when copying from device to host in `tobytes`. Though requires another copy to place the data into the buffer held by the Python `bytes` object.

### CODE REVIEW

**Comment by kkraus14** [comment]
@jakirkham Have you found this faster in practice? I’m concerned about an extra host —> host memory copy.

From my perspective we should just invest the time in building a Cython `HostBuffer` class for now that wraps a `unique_ptr` around the raw pointer from `cudaMallocHost` and then implement buffer protocol and possibly `__array_interface__` on that class. Then we could either return the instance of that class directly or return a `memoryview` of the instance of that class. 

It eliminates the need for the extra host —> host memory copy and will set us up to easily replace the `unique_ptr` wrapping a raw pointer with a `unique_ptr` wrapping an eventual `host_buffer` C++ RAII class when it’s implemented in the future.

Thoughts?

**Comment by jakirkham** [comment]
It still needs some benchmarking. Will work on that in a moment.

I agree that is the right long term plan. Though maybe we also want to align with efforts to provide a pinned memory resource ( https://github.com/rapidsai/rmm/pull/141 ). Should provide us lighter weight wrapping too 😉

Just wanted to see how much mileage we could get out of this relatively simple (though admittedly less efficient approach).

**Comment by jakirkham** [comment]
Yeah the performance here is pretty abysmal. That said, it is much worse than what I would expect from a memory copy. Maybe I'm missing something?

Before:

```python
In [1]: import rmm                                                              

In [2]: rmm.reinitialize(pool_allocator=True, 
   ...:                  initial_pool_size=int(2**30))                          
Out[2]: 0

In [3]: b = rmm.DeviceBuffer(size=10)                                           

In [4]: b.tobytes()                                                             
Out[4]: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [5]: %timeit b.tobytes()                                                     
10.2 µs ± 33.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

After:

```python
In [1]: import rmm                                                              

In [2]: rmm.reinitialize(pool_allocator=True, 
   ...:                  initial_pool_size=int(2**30))                          
Out[2]: 0

In [3]: b = rmm.DeviceBuffer(size=10)                                           

In [4]: b.tobytes()                                                             
Out[4]: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [5]: %timeit b.tobytes()                                                     
1.12 ms ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by kkraus14** [comment]
Allocating host memory is expensive and you're doing it twice instead of once now. This is expected from my perspective.

**Comment by jakirkham** [comment]
> that's ms not us, that's crazy...

No kidding.

> Can you generate a quick Python profile to see if anything sticks out?

Sure I'll take a look. Thanks!

**Pull request closed without merging**
