### PR TITLE
Remove THRUST_WRAPPED_NAMESPACE and tests

### LINKED ISSUE #1577: [FEA] Remove THRUST_WRAPPED_NAMESPACE
**Is your feature request related to a problem? Please describe.**
Since [CCCL 2.3](https://github.com/NVIDIA/cccl/releases/tag/v2.3.0) the Thrust namespace wrapper is no longer required.

**Describe the solution you'd like**
Remove usage of the `THRUST_WRAPPED_NAMESPACE`, `rmm/detail/thrust_namespace.h` and the tests that use it.

### PR DESCRIPTION
**Pull request by harrism**
## Description
Fixes #1577. Removes the no-longer-necessary duplications of tests for `THRUST_WRAPPED_NAMESPACE` 

Wrapping the Thrust namespace is no longer required as of CCCL 2.3 (but is still available if needed). RMM is adopting CCCL 2.5 in release 24.08. 

Eliminating these tests improves build time and reduces testing time by 50%.

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

### CODE REVIEW

**Review by wence- — APPROVED** [review]
:tada: 

Thanks Mark!

One question: does this now make RMM (going forward) incompatible with CCCL < 2.3? If so, should this be marked as a breaking change?

**Comment by bdice** [comment]
In any given release, RAPIDS has a set of dependency pinnings managed by rapids-cmake’s versions.json file. The breaking change, if you would call it that, is in rapids-cmake. I don’t consider this breaking for consumers of RMM because they already have to accept the contract of using RMM’s pinned build-time dependencies.

**Comment by robertmaynard** [comment]
I agree it is a breaking change, since external users of rmm that use `THRUST_WRAPPED_NAMESPACE` will now not work with rmm, even though CCCL 2.5 still supports `THRUST_WRAPPED_NAMESPACE`.

**Comment by harrism** [comment]
> Technically `THRUST_WRAPPED_NAMESPACE` still has a usage, and that is when a consumer leaks Thrust types in the public API. In those cases you would want to still use `THRUST_WRAPPED_NAMESPACE` so that you are safe to be composed with other libraries that use a different version of Thrust.

Apologies, I misunderstood. I thought THRUST_WRAPPED_NAMESPACE was a necessary evil that is no longer necessary.  I will revert all but the test changes.  I don't like that we have to keep remembering to include `thrust_namespace.h [sic]` in all files that call thrust. Hopefully we can completely eliminate it in the future.

**Review by bdice — APPROVED** [review]

**Review by miscco — APPROVED** [review]

**Pull request merged**
