### PR TITLE
WIP: Add `__cuda_memory__` attribute to `DeviceBuffer`

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by kkraus14** [comment]
@jakirkham can you explain what this `__cuda_memory__` protocol is for?

**Comment by jakirkham** [comment]
Discovered this when looking into `auto_device` in issue ( https://github.com/rapidsai/rmm/issues/265 ). It appears that Numba uses this in some places internally. Requested some more info in issue ( https://github.com/numba/numba/issues/5168 ). We can probably wait on this PR until we get some more info from them.

**Comment by kkraus14** [comment]
cc @gmarkall maybe you can shed some light on this?

**Comment by raydouglass** [comment]
rerun tests

**Comment by jakirkham** [comment]
FWIW I dug into the source code a bit. AIUI `__cuda_memory__` just means we supply an attribute called `device_pointer`, which is analogous to what we have as `ptr` now. We may also want to add the attribute `_cuda_memsize_`, which would be the same as our `size`. IIUC this would allow us to build `DeviceNDArray`s directly using `DeviceBuffer` as `gpu_data`, which would bypass context grabbing behavior [that seems to slow things down for us]( https://github.com/rapidsai/ucx-py/issues/402#issuecomment-580061200 ).

**Comment by harrism** [comment]
Should this move to 0.14 or will it get done in 0.13?

**Comment by jakirkham** [comment]
Actually I'm going to go ahead and close this for now. We can revisit later as needed. Thanks all! 😄

**Comment by gmarkall** [comment]
> FWIW I dug into the source code a bit. AIUI `__cuda_memory__` just means we supply an attribute called `device_pointer`, which is analogous to what we have as `ptr` now. We may also want to add the attribute `_cuda_memsize_`, which would be the same as our `size`. IIUC this would allow us to build `DeviceNDArray`s directly using `DeviceBuffer` as `gpu_data`, which would bypass context grabbing behavior [that seems to slow things down for us](https://github.com/rapidsai/ucx-py/issues/402#issuecomment-580061200).

I think that just setting `__cuda_memory__`, `__cuda_memsize__` and `device_pointer` will result in odd things happening inside Numba - there are assumptions in various places that the `gpu_data` is a `MemoryPointer` or something quite like it. I'm not sure exactly what would go wrong, but I can look into what would need to change if we wanted to pass `DeviceBuffer`s as `gpu_data` - is that of interest?

**Pull request closed without merging**
