### PR TITLE
Update CMakeLists.txt VERSION to 0.18.0

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by kkraus14** [comment]
Can you fix this as well to automatically handle it moving forward: https://github.com/rapidsai/rmm/blob/branch-0.18/ci/release/update-version.sh#L48

**Comment by trxcllnt** [comment]
@kkraus14 I ran that script to produce this change. Maybe the commit that updates the RMM version hasn't been merged into the new branch yet?

**Comment by kkraus14** [comment]
cc @rapidsai/ops

**Comment by hcho3** [comment]
Any updates on this PR? Can we merge it?

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
