### PR TITLE
Include rmm/detail/error.hpp to get the `RMM_CUDA_TRY` macro

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by trxcllnt** [comment]
I'm not in the rmm-codeowners group, otherwise I'd add the labels.

**Review by rongou — APPROVED** [review]

**Comment by jrhemstad** [comment]
@gpucibot merge

**Comment by jrhemstad** [comment]
rerun tests

**Comment by trxcllnt** [comment]
```
[2021-04-20T14:50:41.704Z] Setting status of cc6d25e9ffce3652696ab5bf45f2b9752a7f8039 to SUCCESS with url https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci-v0.20/job/rmm/job/prb/job/rmm-prb/29/ and message: 'Build succeeded
[2021-04-20T14:50:41.704Z]  '
[2021-04-20T14:50:41.704Z] Using context: gpuCI/rmm/pr-builder
[2021-04-20T14:50:41.744Z] Could not update commit status of the Pull Request on GitHub.
[2021-04-20T14:50:41.744Z] org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

**Pull request merged**
