### PR TITLE
use cuda allocation alignment as default

### PR DESCRIPTION
**Pull request by rongou**
This is a strict refactoring to make the calling code a bit simpler.

### CODE REVIEW

**Review by jrhemstad — CHANGES_REQUESTED** [review]
Once https://github.com/rapidsai/rmm/pull/883 is complete, there will be nothing special about `CUDA_ALLOCATION_ALIGNMENT` vs any other specified alignment value that warrants defaulting it like this.

**Comment by rongou** [comment]
Hmm, but in #883 we are still calling (e.g. in `binning_memory_resource`):
```cpp
allocation_size =
  rmm::detail::align_up(allocation_size, rmm::detail::CUDA_ALLOCATION_ALIGNMENT)
```
Don't we still need to do this type of alignments?

**Comment by jrhemstad** [comment]
> Hmm, but in #883 we are still calling (e.g. in `binning_memory_resource`):
> 
> ```c++
> allocation_size =
>   rmm::detail::align_up(allocation_size, rmm::detail::CUDA_ALLOCATION_ALIGNMENT)
> ```
> 
> Don't we still need to do this type of alignments?

The new interface allows the user to specify the desired alignment. The default will be `max_align_t`, but that default is provided at the interface level, not internally in a function like this.

**Comment by rongou** [comment]
Wouldn't it still make sense to do this simple cleanup while we wait for the new interface?

**Review by harrism — APPROVED** [review]

**Comment by harrism** [comment]
> Wouldn't it still make sense to do this simple cleanup while we wait for the new interface?

Possibly, given that #883 and `cuda::memory_resource` are dragging...

**Comment by harrism** [comment]
Moving to 22.04

**Comment by rongou** [comment]
rerun tests

**Comment by rongou** [comment]
@harrism should this be merged?

**Comment by harrism** [comment]
@jrhemstad needs to approve.

**Comment by Ethyling** [comment]
rerun tests

**Pull request closed without merging**
