### PR TITLE
[REVIEW] Avoids typo and gender/class insensitivity

### PR DESCRIPTION
**Pull request by gonzalobg**
Avoids typo and gender/class insensitivity

cc @harrism

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by harrism** [comment]
Hmmm, let's put this change in another open PR, so that it doesn't have to have its own CHANGELOG entry.  I'll put it into one of my current PRs.

**Comment by gonzalobg** [comment]
Thank you. I've reported this here: https://github.com/rapidsai/rmm/issues/552 Should probably fixed at the bot level.

If somebody points me to the bot's source I can fix that.

**Pull request closed without merging**
