### PR TITLE
Add `shape` property to `DeviceBuffer`

### PR DESCRIPTION
**Pull request by jakirkham**
As some libraries that take array-like data expect that data to have an `shape` property, go ahead and add one to `DeviceBuffer`.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by kkraus14** [comment]
@jakirkham this seems out of scope for a DeviceBuffer object. I understand the need for `__cuda_array_interface__` for now, but these are array attributes which a DeviceBuffer is not trying to be. I think of this as similar to a `bytes` or `bytearray` object in Python, where they implement buffer protocol, but there isn't array attributes associated with it.

**Comment by jakirkham** [comment]
Superseded by PR ( https://github.com/rapidsai/rmm/pull/212 ).

**Comment by jakirkham** [comment]
@kkraus14, @harrism asked for these to be consolidated into one PR. Is it ok if we continue the conversation in PR ( https://github.com/rapidsai/rmm/pull/212 )?

**Pull request closed without merging**
