### PR TITLE
Treat warnings as errors in Python documentation

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This will allow us to more easily audit the quality of our docs in CI going forward.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by wence- — APPROVED** [review]

**Review by ajschmidt8 — COMMENTED** [review]
same question as below

- https://github.com/rapidsai/cudf/pull/13789#discussion_r1280653303

**Comment by vyasr** [comment]
> same question as below
> 
>     * [Fix all warnings in Python docs cudf#13789 (comment)](https://github.com/rapidsai/cudf/pull/13789#discussion_r1280653303)

Addressed it in the other PR. We're going to move towards `make` from `sphinx-build` everywhere.

**Review by ajschmidt8 — APPROVED** [review]

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
blocking while I investigate a potential error with the changes from the preview environments

**Comment by ajschmidt8** [comment]
posted my findings in the `cudf` PR: https://github.com/rapidsai/cudf/pull/13789#discussion_r1283489007

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
