### PR TITLE
Fix Cmake LOGGING_LEVEL so that default logging is not verbose and expensive

### PR DESCRIPTION
**Pull request by harrism**
Fixes the cmake for LOGGING_LEVEL so that it's actually possible to turn it OFF. Also renames to RMM_LOGGING_LEVEL.

Also, the LOGGING_LEVEL variable handling was being done *After* `add_subdirectory(benchmark)` which meant that the variable was not set the first time benchmarks were built after a clean. This resulted in logging being compiled at trace level, causing benchmark regressions. This PR reorders the cmake.

This fixes a performance regression (on initial builds) reported in #543

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by kkraus14 — APPROVED** [review]
Agreed that naming is a bit awkward but CMake LGTM

**Comment by kkraus14** [comment]
rerun tests

**Review by rongou — APPROVED** [review]

**Comment by harrism** [comment]
> Agreed that naming is a bit awkward but CMake LGTM

Definitely open to improvement suggestions. Ideas?

**Comment by rongou** [comment]
I think all you need to do is this:
```cmake
set(LOGGING_LEVEL "INFO" CACHE STRING "Choose the logging level.")
# Set the possible values of build type for cmake-gui
set_property(CACHE LOGGING_LEVEL PROPERTY STRINGS
    "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "CRITICAL" "OFF")
```
To turn logging off:
```console
cmake .. -DLOGGING_LEVEL=OFF
```

**Comment by rongou** [comment]
A bit of explanation on why this works. Without the `FORCE` attribute, a cache variable can be set by the user from the command line. If it's not set, the default is `INFO`.

**Comment by germasch** [comment]
> ```cmake
> set(LOGGING_LEVEL "INFO" CACHE STRING "Choose the logging level.")
> # Set the possible values of build type for cmake-gui
> set_property(CACHE LOGGING_LEVEL PROPERTY STRINGS
>     "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "CRITICAL" "OFF")
> ```

This looks good to me (though I haven't tried).

An unrelated comment: If the name of the variable isn't set in stone yet, I think it's preferable to use prefixed names, like `RMM_LOGGING_LEVEL`. The reason is that if, say, cudf includes rmm via `add_subdirectory`, rmm will pick up a potential `LOGGING_LEVEL` variable from cudf, which may not be what's intended.

**Comment by harrism** [comment]
> > ```cmake
> > set(LOGGING_LEVEL "INFO" CACHE STRING "Choose the logging level.")
> > # Set the possible values of build type for cmake-gui
> > set_property(CACHE LOGGING_LEVEL PROPERTY STRINGS
> >     "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "CRITICAL" "OFF")
> > ```
> 
> This looks good to me (though I haven't tried).
> 
> An unrelated comment: If the name of the variable isn't set in stone yet, I think it's preferable to use prefixed names, like `RMM_LOGGING_LEVEL`. The reason is that if, say, cudf includes rmm via `add_subdirectory`, rmm will pick up a potential `LOGGING_LEVEL` variable from cudf, which may not be what's intended. 
> 

Ok, thanks @rongou and @germasch . Good advice. However setting -DLOGGING_LEVEL=OFF does not set the variable to off, it sets it to undefined. I have tested this. This is the root of the problem.

**Comment by germasch** [comment]
> Ok, thanks @rongou and @germasch . Good advice. However setting -DLOGGING_LEVEL=OFF does not set the variable to off, it sets it to undefined. I have tested this. This is the root of the problem.

Did you try with exactly @rongou's suggestion (incl. `STRING`)?
```
set(LOGGING_LEVEL "INFO" CACHE STRING "Choose the logging level.")
message("LOGGING_LEVEL = ${LOGGING_LEVEL}")
```
works for me, including with `cmake -DLOGGING_LEVEL=OFF`.

**Comment by harrism** [comment]
Yes, it does work. Before we had `if(NOT LOGGING_LEVEL)` before the `set(LOGGING_LEVEL)`. And in that case `-DLOGGING_LEVEL=OFF`  was causing the if() to evaluate true, so it was being reset to INFO.   But I misinterpreted that as OFF being treated the same as "unset".

**Review by cwharris — APPROVED** [review]
lgtm

**Review by codereport — APPROVED** [review]

**Review by kkraus14 — APPROVED** [review]

**Comment by harrism** [comment]
Not willing to wait for A100 CI, @kkraus14 ?

**Pull request merged**
