### PR TITLE
WIP: Prevent path conflict in builds

### LINKED ISSUE #1528: [BUG] Conda package for rmm 24.04.00 clobbering files from fmt and spdlog
**Describe the bug**
Looking at `librmm-24.04.00-cuda12_240410_g8f19c9c3_0.tar.bz` from the rapidsai conda channel I see multiple warnings about clobbered files from `fmt` and `spdlog`.

**Steps/Code to reproduce bug**
I downloaded https://anaconda.org/rapidsai/librmm/24.04.00/download/linux-64/librmm-24.04.00-cuda12_240410_g8f19c9c3_0.tar.bz2 and untarred, I see multiple files that are installed to paths that conflict such as `lib/libfmt.a`, `lib/libspdlog.a`, `include/fmt/color.h`, `include/spdlog/common.h` that cause conflicts.

**Expected behavior**
The vendored files should be installed in paths that would not cause conflicts with other packages.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker]
 - Method of RMM install: conda

### PR DESCRIPTION
**Pull request by AyodeAwe**
Fixes #1528.

Contributes to https://github.com/rapidsai/build-planning/issues/54 and https://github.com/rapidsai/build-planning/issues/56.

Related to https://github.com/rapidsai/rapids-cmake/pull/592

## Notes for Reviewers

This is not ready for review yet.

Related conversations:

* #1177

### CODE REVIEW

**Comment by jameslamb** [comment]
This is currently failing with the following conflicts.

*(I've included just 1 example of each type below)* ([click here for the full build log](https://github.com/rapidsai/rmm/actions/runs/8759221737/job/24041807014?pr=1508))

1. `fmt` headers in `include/fmt`

```text
This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-aarch64::fmt-10.2.1-h2a328a1_0, file:///tmp/conda-bld-output/linux-aarch64::librmm-24.06.00a16-cuda12_240419_g9dfd9070_16
  path: 'include/fmt/chrono.h'
```

2. `fmt` builds scripts in `lib/cmake/fmt/

```text
This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-aarch64::fmt-10.2.1-h2a328a1_0, file:///tmp/conda-bld-output/linux-aarch64::librmm-24.06.00a16-cuda12_240419_g9dfd9070_16
  path: 'lib/cmake/fmt/fmt-targets.cmake'
```

3. `fmt` pkgconfig script

```text
This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-aarch64::fmt-10.2.1-h2a328a1_0, file:///tmp/conda-bld-output/linux-aarch64::librmm-
  path: 'lib/pkgconfig/fmt.pc'
```

4. `spdlog` headers

```text
This transaction has incompatible packages due to a shared path.
   packages: conda-forge/linux-aarch64::spdlog-1.12.0-h6b8df57_2, file:///tmp/conda-bld-output/linux-aarch64::librmm-24.06.00a16-cuda12_240419_g9dfd9070_16
   path: 'include/spdlog/async.h'
```

5. `spdlog` build scripts

```text
This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-aarch64::spdlog-1.12.0-h6b8df57_2, file:///tmp/conda-bld-output/linux-aarch64::librmm-24.06.00a16-cuda12_240419_g9dfd9070_16
  path: 'lib/cmake/spdlog/spdlogConfig.cmake'
```

6. `spdlog` pkgconfig script

```text
This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-aarch64::spdlog-1.12.0-h6b8df57_2, file:///tmp/conda-bld-output/linux-aarch64::librmm-24.06.00a16-cuda12_240419_g9dfd9070_16
  path: 'lib/pkgconfig/spdlog.pc'
```

**Comment by jameslamb** [comment]
@harrism I don't think the clobbering stuff is what's causing that PR to fail (although it is generating thousands of lines of scary-looking logs 😅 ).

#1537 is failing because it removes a file but not the corresponding test in the conda recipe.

```text
+ test -f /opt/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include/rmm/thrust_rmm_allocator.h
WARNING: Tests failed for librmm-24.06.00a20-cuda12_240423_ga4d6c965_20.tar.bz2 - moving package to /opt/conda/conda-bld/broken
```

Remove this test there:

https://github.com/rapidsai/rmm/blob/9e6db746f1a4a6361fb9fadf381f749dc52faaea/conda/recipes/librmm/meta.yaml#L84

**Comment by harrism** [comment]
Oh how did you even find that? I just saw all the ClobberWarnings.

**Comment by harrism** [comment]
Any way to make those failures fail with the text "error:"? This is usually what I search for in the logs.

**Comment by jameslamb** [comment]
> *Oh how did you even find that? I just saw all the ClobberWarnings.*

I went straight to the end of the log and read back up from there until I saw something problematic. A lot of the CI scripts across RAPIDS have `set -e -u -o pipefail` set, so they tend to fail at the first place where something goes wrong.

I also had _just_ looked at these tests in the `conda` recipe today, in the process of testing for this PR, so had some pattern recognition for what it looked like when they failed.

> *Any way to make those failures fail with the text "error:"? This is usually what I search for in the logs.*

Not that I'm aware of. That comes from within `conda` itself, I don't think we can control it.

It does say "fail" which I usually search for along with "error".

```text
...
WARNING: Tests failed for librmm-24.06.00a20-cuda11_240423_ga4d6c965_20.tar.bz2 - moving package to /opt/conda/conda-bld/broken
...
TESTS FAILED: librmm-24.06.00a20-cuda11_240423_ga4d6c965_20.tar.bz2
[rapids-conda-retry] conda returned exit code: 1
```

([build link](https://github.com/rapidsai/rmm/actions/runs/8795230805/job/24136012473))

**Comment by harrism** [comment]
Will this make it into 24.06?

**Comment by jameslamb** [comment]
> Will this make it into 24.06?

**short answer**

Not unless we decide that there's an urgent need for it.

**long answer**

The root cause of these `fmt` and `spdlog` clobbering issues across RAPIDS is *"RAPIDS is carrying around patches to those libraries, so `rapids-cmake` always downloads them, and it places them at likely-to-cause-conflicts paths like `include/fmt`"*.

I'd started pursuing a short-term fix (upgrade to newer versions of `fmt` and `spdlog` that don't need the patches), described in https://github.com/rapidsai/build-planning/issues/56 and tested over in #1544.

Stopped short of trying to roll that out across all of RAPIDS conda packages, because doing it might lead to RAPIDS packages conflicting with `conda` itself and other packages from `conda-forge`. @bdice summarized that well here: https://github.com/rapidsai/build-planning/issues/56#issuecomment-2087365946

At that point, we paused on this to work towards other packaging priorities for this release: https://github.com/rapidsai/build-planning/issues/54#issuecomment-2093814987

I'd like to pick up a more permanent solution (RAPIDS redistributing these things when necessary, via its own conda package built from `rapids-cmake`) in the next release cycle.

cc @mmccarty for visibility

**Comment by harrism** [comment]
Thanks. Moving to backlog.

**Comment by jameslamb** [comment]
This work is paused, in favor of pursuing a better long-term solution in the future. Closing this PR for now.

Subscribe to https://github.com/rapidsai/build-planning/issues/54 and https://github.com/rapidsai/build-planning/issues/56 for updates.

**Pull request closed without merging**
