### PR TITLE
Enabling/disabling logging after initialization

### PR DESCRIPTION
**Pull request by shwina**
This PR adds the ability to enable/disable loggin after RMM has been initialized, _without destroying/ any existing memory resources_.

To do this, we wrap any existing memory resources in `LoggingMemoryResource`  when `enable_logging()` is called. Conversely, when `disable_logging()` is called, we replace any `LoggingMemoryResources` with their upstream resources.

For this to work correctly, `LoggingMemoryResource` needs to keep a reference to its upstream resource. We must then use `__dealloc__` to ensure that the upstream doesn't get deleted first when the `LoggingMemoryResource` goes out of scope. (see https://github.com/rapidsai/rmm/pull/662/).

Closes https://github.com/rapidsai/rmm/issues/423

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
@gpucibot merge

**Comment by kkraus14** [comment]
Looks like you're segfaulting 😄

**Comment by rlratzel** [comment]
Thanks for working on this, @shwina !  Here's the feedback we went over offline that you requested I post here:

> We plan on using this to track GPU memory usage as part of a benchmarking plugin to pytest.  
I'm wondering if it'll be a problem if the code being benchmarked may also attempt to enable logging for its own purposes, with its own file name.  Should that be addressed?
> 
> The ideal but possibly non-trivial solution would be to have `rmm.enable_logging()` return a reference that would be passed to disable:
> ```
> log_id = rmm.enable_logging(log_file_name="tmpfile")
> # run code to benchmark
> rmm.disable_logging(log_id)
> # open tmpfile and figure out mem used/leaked
> # remove tmpfile
> ```
> The idea there is that I'd get my own unique log_id, and RMM would support logging to possibly multiple files. That would allow the code being benchmarked to also use logging for its own purposes (another interesting use case for this would be to have a RMM log for an entire application, then possibly a separate log for a critical section).  But maybe at a minimum we should raise an exception if we're about to clobber an already open default logging session?

**Comment by shwina** [comment]
@jrhemstad It sounds like this would need the ability for `logging_resource_adaptor` to support multiple sinks, with the ability to add or remove sinks. From a cursory search, it looks like that's a use-case spdlog supports. Can this be added to librmm?

**Comment by jrhemstad** [comment]
Multiple sinks can work, but I don't think dynamically adding/removing sinks is possible. If you want to change the sinks you'd have to construct a new `logging_resource_adaptor` with the new desired sinks.

**Pull request merged**
