### PR TITLE
Build.sh use cmake --build to drive build system invocation

### LINKED ISSUE #685: [BUG] build.sh can fail when environment variable `CMAKE_GENERATOR` is set
**Describe the bug**

When executing the `build.sh` script if the `CMAKE_GENERATOR` environment variable is to `Ninja` the compilation step will fail as it expects a makefile to exist. 

**Steps/Code to reproduce bug**

Reproducible with:

```
CMAKE_GENERATOR="Ninja" ./build.sh librmm
```

**Expected behavior**

Expected the `build.sh` script to either invoke `cmake --build <dir>` to remove any assumptions on which generator was selected, or explicitly specify the generator.

### PR DESCRIPTION
**Pull request by robertmaynard**
Closes #685

By using `cmake --build` instead of explicitly invoking the presumed underlying build system we allow for different CMake generators to be supported.

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]
changes LGTM, thanks @robertmaynard!

**Comment by kkraus14** [comment]
@robertmaynard any other changes planned in this PR or is this good to go?

**Comment by robertmaynard** [comment]
> @robertmaynard any other changes planned in this PR or is this good to go?

This is good to go.

**Comment by kkraus14** [comment]
@gpucibot merge

**Pull request merged**
