### PR TITLE
[WIP] Windows compilation

### PR DESCRIPTION
**Pull request by karthikeyann**
## Description
The changes in this PR allow windows compilation to succeed for librmm and their tests to pass (some fail TBD).

#### Windows Setup:
- Visual Studio 2022 - 17.6.4 (MSVC v143)
  cl.exe Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x64
- vcpkg
- CUDA 12.1
- cmake-3.27.0
- ninja v1.11.1 binary
- miniconda

#### Environment Setup:
`conda env create --name rmm_dev --file conda/environments/all_cuda-120_arch-x86_64.yaml`
`vcpkg install pthread:x64-windows`
`conda install -c conda-forge dlfcn-win32`

#### Compilation:
- Open Anaconda prompt
- Run vcvars32.bat or vcvars64.bat file to allow msvc compilation
- `conda activate rmm_dev`
- `mkdir build; cd build`, `mkdir ..\..\install`
- `cmake .. -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=..\..\install -DCMAKE_TOOLCHAIN_FILE=C:/Users/karthikeyann/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake`
- `cmake --build .`

#### Changes after cmake configure attempt:
rapids-cmake comment out compilation code in 
`C:\Users\karthikeyann\Desktop\rmm\build\_deps\rapids-cmake-src\rapids-cmake\test\generate_resource_spec.cmake`
and update the cuda compute capability minor, major version in same file.

Renamed `C:\Users\karthikeyann\Desktop\rmm\build\_deps\thrust-src\cub` symlink to cub2.
msvc does not support symlink within pre-processor.
so, copied folder `C:\Users\karthikeyann\Desktop\rmm\build\_deps\thrust-src\dependencies\cub\cub`
to 
`C:\Users\karthikeyann\Desktop\rmm\build\_deps\thrust-src\cub`

#### List of code changes:
- RMM_EXPECTS, RMM_FAIL [macro vaargs workarounds](https://developercommunity.visualstudio.com/t/-va-args-seems-to-be-trated-as-a-single-parameter/460154)
- add dlfcn, remove cuda-nvcc, cuda-python in dependency, 
- enable [Alternative operator representations](https://en.cppreference.com/w/cpp/language/operator_alternative) (and, or, not) using [header \<ciso646\>](https://en.cppreference.com/w/cpp/header/ciso646)
- fix macro inside gtest macro issue
- fix missing lambda capture
- fix posix mkdtemp, setenv, unsetenv
- workaround for CTAD constructor template argument missing feature
- disable int8_t because it is not by <random>uniform_int_distribution
- ULL for 64 bit unsigned integer. See https://en.cppreference.com/w/cpp/language/types#Data_models
- fix for "auto*" unsupported.
- hack for move-only type with std::set and move constructor invoking copy constructor issue. (TBD proper fix), ([bug](https://developercommunity.visualstudio.com/t/bug-in-stdmapstdpair-implementation-with-move-only/840554))
- pthread library name to pthreadVC3, cudart dll name.

All  `*/CUDA_Async`  tests are skipped, as this driver version is unsupported (TBD).

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by jrhemstad** [comment]
Note that RMM is structurally incompatible with Windows as a header-only library as the functionality of `per_device_resource()` depends on function local statics being shared across TUs. See https://stackoverflow.com/questions/62336104/are-function-local-static-objects-of-inline-functions-shared-across-shared-objec#comment110248896_62336104 

RMM would need to build a DLL that holds the symbols relevant for `per_device_resource`.

**Comment by harrism** [comment]
Do we have Windows CI?

**Comment by jrhemstad** [comment]
> Do we have Windows CI?

Not yet. We're working on it as CCCL needs it, but it's still many months away.

**Comment by bdice** [comment]
I'm going to close this PR since this is not an active area of focus. If we re-open this work, we would probably want to do it from a fresh PR since this one is fairly out of date.

**Pull request closed without merging**
