### PR TITLE
[REVIEW] Proposal: Add device memory limit

### PR DESCRIPTION
**Pull request by takeshi-yoshimura**
So far I have been working on RAPIDS with larger working sets than GPU memory. Let me contribute my finding here as PR.

Currently, RMM does not provide configurations for limiting the amount of GPU memory for each app. As a result, it is difficult to run multiple RAPIDS and other CUDA jobs on the same GPU even if it is underutilized. Managed memory in RMM enables us to consolidate apps, but from my observations, it degraded performance unpredictability and does not allow us to prioritize particular apps by configuring larger GPU memory. I believe future dask-cudf/cuml should have this kinds of memory configurations for optimizing large-scale, complex data processing as done by Spark and Hadoop.

In this PR, I would like to propose a new configuration, limit_device_memory to enable users to set the maximum amount of GPU memory RAPIDS can allocate. I guess this configuration is not perfect and should be enhanced more in near future (e.g., memory limit across processes), but I believe this is a good starting point to enhance RAPIDS for consolidated environments.

I also introduced another configuration CudaHostAllocMemory to avoid OOM if the allocation exceeds the configured limit. This configuration uses pinned host memory instead of device memory. cuDF on host memory looks working (of course, a bit slow) as far as my tests for cudf load, sort, and hash/sort merge with skylake and ppc64le + V100 GPU.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by dillon-cullinan** [comment]
okay to test

**Comment by harrism** [comment]
We're in the process of transitioning to using a memory resource based allocation model, which will make it possible to support more options like this without all the complex nested ifs, so I will probably wait to consider this change until that is in place.

**Comment by takeshi-yoshimura** [comment]
Thank you for your reply. I think the change will be great for our use-cases of rapids. I will wait for your update!

**Comment by quasiben** [comment]
@pentschev this PR may interest you given recent work on device spilling

**Comment by harrism** [comment]
@takeshi-yoshimura RMM has changed significantly since this PR.  The new pool_memory_resource has a configurable maximum pool size. I'm going to close this.

**Pull request closed without merging**
