### PR TITLE
[REVIEW] Create gpuCI build scripts

### PR DESCRIPTION
**Pull request by raydouglass**
This is my initial pass at the gpuCI build scripts.

The jobs still need to be created and configured.

### CODE REVIEW

**Comment by harrism** [comment]
@raydouglass please remember to add a CHANGELOG item (since CI won't remind you).

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by harrism** [comment]
@raydouglass I created #49 to fix the style failures but it seems that CI is already active on new PRs, even though the scripts (in this PR) have not been merged yet... So the CI on #49 failed.

**Comment by harrism** [comment]
Merged #49 anyway. rerun tests.

**Comment by harrism** [comment]
OK, so even though I merged the fixes to the flake8 failures, when I reran the tests it still got the same errors. @raydouglass can you merge the latest branch-0.6 into this branch?

**Comment by harrism** [comment]
Nevermind, it appears I was wrong and style passed. Only thing left is the changelog.

**Comment by raydouglass** [comment]
rerun tests

**Pull request merged**
