### PR TITLE
Synchronize stream in `DeviceBuffer.c_from_unique_ptr` constructor

### PR DESCRIPTION
**Pull request by shwina**
The `DeviceBuffer.__cinit__` method syncs the default stream to ensure that access to the `.ptr` and `.size` attributes of the underlying `rmm::device_buffer` is safe.

However, the staticmethod `DeviceBuffer.c_from_unique_ptr` does not. This PR adds a stream sync to it.

### CODE REVIEW

**Comment by shwina** [comment]
rerun tests

**Review by harrism — APPROVED** [review]

**Comment by shwina** [comment]
rerun tests

**Comment by harrism** [comment]
@ashwin is this a 22.10 code freeze blocker? If you merge the latest 22.10 branch CI should work now.

**Comment by harrism** [comment]
I missed this PR because it is not assigned to a project.

**Comment by ashwin** [comment]
@shwina I believe the above query from Mark Harris is meant for you. 😊

**Comment by harrism** [comment]
Oops, sorry.

**Comment by shwina** [comment]
Retargeting, as I don't want to introduce this change so late into the release. So far it has never bitten us...

**Review by jakirkham — APPROVED** [review]

**Comment by shwina** [comment]
rerun tests

**Comment by vyasr** [comment]
@shwina should we get this into 23.04? Seems like it dropped off all our radars but not for any particular reason.

**Comment by jakirkham** [comment]
Retargeted to `branch-23.04`

**Comment by jakirkham** [comment]
Thanks all! 🙏

If we find anything else is needed here, please raise an issue (or PR) and we can follow up from there 🙂

**Pull request merged**
