### PR TITLE
[REVIEW] unpin spdlog so that it can move to 1.8.1 or above

### PR DESCRIPTION
**Pull request by rongou**
The problem from #542 should be fixed.

@harrism @kkraus14

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
add to whitelist

**Review by kkraus14 — DISMISSED** [review]

**Comment by kkraus14** [comment]
```
/opt/conda/envs/rapids/conda-bld/librmm_1601527198390/work/build/_deps/spdlog-src/include/spdlog/fmt/bundled/format.h(3677): error: a literal operator template must have a template parameter list equivalent to "<char ...>"
```

Looks like there's still an issue in 1.8.1 for CUDA 10.1 / 10.2?

**Comment by rongou** [comment]
@kkraus14 hmm it's possible. I only built it with cuda 11. Let me try the older versions.

**Comment by harrism** [comment]
This was the error that prevented us using spdlog 1.8.0 before. I expected it to be fixed by https://github.com/fmtlib/fmt/pull/1818 which I think is in 1.8.1  but I'm not positive...

**Review by ajschmidt8 — COMMENTED** [review]
the `spdlog` version in the integration repo will also need to be updated.

https://github.com/rapidsai/integration/blob/branch-0.16/conda/recipes/versions.yaml#L116

**Comment by rongou** [comment]
Argh looks like that fix just missed the fmt release so it didn't get into spdlog. I guess we'll just have to wait for a bit.

**Pull request closed without merging**
