### PR TITLE
Remove un-need judgements

### PR DESCRIPTION
**Pull request by JustPlay**
Remove un-need if judgements

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by harrism — CHANGES_REQUESTED** [review]
This is incorrect logic. With your change it would be possible to pick block b even if it doesn't fit. To be a better fit this block must fit and either b must not fit or this block must be smaller than b.

The existing code is correct.

**Comment by JustPlay** [comment]
> This is incorrect logic. With your change it would be possible to pick block b even if b is not big enough. To be a better fit this block must fit and either b must not fit or this block must be smaller than b.
> 
> The existing code is correct.

O, thanks very mush.

**Pull request closed without merging**
