### PR TITLE
[REVIEW] Check that clang is only used with the C++11 ABI

### PR DESCRIPTION
**Pull request by gonzalobg**
Error if clang is used with the C++03 ABI.

I've only verified that it works with the C++11 ABI. On my environment, clang fails to link when the C++03 ABI is used. 

I didn't investigate much, but googletest symbols were not found when linking the tests. It appears that clang was expecting C++11 symbols, but these were not available (probably because googletest was built with the C++03 ABI).

It might be possible to workaround this. I've opened https://github.com/rapidsai/rmm/issues/548 to track it.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by germasch** [comment]
A related question: What's the history of disabling the cxx11 ABI? Is that something that is really still necessary? (I think it's necessary when using rmm with a project that deliberately chooses the old ABI and can't be update.

I'm kinda wondering how many such projects are around? -- also considering that rmm seems to, e.g., not maintain support for old cuda versions for long.

**Comment by kkraus14** [comment]
> A related question: What's the history of disabling the cxx11 ABI? Is that something that is really still necessary? (I think it's necessary when using rmm with a project that deliberately chooses the old ABI and can't be update.

I think this is a remnant of conda-forge using old ABI prior to a big compiler migration they did.

> I think it's necessary when using rmm with a project that deliberately chooses the old ABI and can't be update.

In this case they could always set the relevant flags variables themselves to still get an old ABI build.

> Is that something that is really still necessary?

At this point I think we're safe to remove it.

**Comment by kkraus14** [comment]
Fixed by #550

**Comment by gonzalobg** [comment]
> I think this is a remnant of conda-forge using old ABI prior to a big compiler migration they did.

GCC broke the libstdc++ ABI when implementing C++11 support. The ABI of types like `string` and `vector` changed, breaking all code compiled against the previous C++03 ABI. 

That is, a new C++11 ABI version of libstdc++ was released. Many distros took a long time to switch (particularly LTS ones), many distros also shipped and some continue to ship two versions of libstdc++, one with each ABI. 

See here for the details: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

> In this case they could always set the relevant flags variables themselves to still get an old ABI build.

Depends on whether your build system passes these properties to third-party dependencies like GoogleTest that also need to be built as part of this library. This could work, but the build system might need to cooperate. 

> At this point I think we're safe to remove it.

Might want to open an issue in case somebody needs to support environments that only have the C++03 ABI available.

**Pull request closed without merging**
