### PR TITLE
Remove upper bounds on cuda-python to allow 12.6.2 and 11.8.5

### PR DESCRIPTION
**Pull request by bdice**
Now that some upstream bugs have been fixed, we can allow cuda-python 12.6.2 and 11.8.5.

See https://github.com/NVIDIA/cuda-python/issues/226#issuecomment-2472355738 for more information.

### CODE REVIEW

**Comment by harrism** [comment]
I assume this will move to 25.02?

**Comment by bdice** [comment]
Yes, we are discussing this for 25.02. https://github.com/rapidsai/build-planning/issues/117 has more context. I'll retarget it to 25.02 for now.

**Comment by vyasr** [comment]
@bdice I've updated this branch. I think we are good to merge now.

**Comment by bdice** [comment]
@vyasr Sounds good. I opened this for review. We can merge once reviews are done.

**Pull request merged**
