### PR TITLE
[RELEASE] v0.6 RMM Release

### PR DESCRIPTION
**Pull request by mike-wendt**
### What does this mean?
Only hotfix and/or critical bug level issues should be merged into `branch-0.6` until release (merging of this PR).

### What is the purpose of this PR?
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-0.6` into `master` for the release

### CODE REVIEW

**Comment by mike-wendt** [comment]
rereun tests

**Comment by harrism** [comment]
I think @mike-wendt means rerun tests

:)

**Comment by mike-wendt** [comment]
@harrism ready to release when you approve

**Comment by mike-wendt** [comment]
@harrism are we good to release?

**Comment by mike-wendt** [comment]
Going to release, will re-release if there are issues so we can get cuStrings updated and packaged

**Comment by harrism** [comment]
All good.

**Pull request merged**
