### PR TITLE
Remove `no_cma`/`has_cma` variants

### PR DESCRIPTION
**Pull request by ajschmidt8**
Depends on #990.

Once #990 is merged, we should no longer need the `no_cma`/`has_cma` `rmm` package variants. This PR removes the two variants.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
Keeping as a draft in case these changes are decided to be included in #990.

**Comment by robertmaynard** [comment]
We should remove the root directory `build.sh` cma hooks as well. Plus we can remove the root CMakeLists.txt and the python/CMakeLists.txt usage of `CUDA_MALLOC_ASYNC_SUPPORT`

**Comment by ajschmidt8** [comment]
> We should remove the root directory `build.sh` cma hooks as well. Plus we can remove the root CMakeLists.txt and the python/CMakeLists.txt usage of `CUDA_MALLOC_ASYNC_SUPPORT`

removed in 5425c47

**Review by robertmaynard — APPROVED** [review]

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Pull request merged**
