### PR TITLE
[REVIEW] Add .clang-format file & format all files

### PR DESCRIPTION
**Pull request by codereport**
Resolves https://github.com/rapidsai/rmm/issues/349

Add clang-format. config file from cuDF was used.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by harrism** [comment]
Wait you are making manual formatting changes? I thought clang-format made that unnecessary and counter productive?!

BTW I don't like the comment approach to solving the clang-format issue with #endif -- isn't there a better way?

**Comment by codereport** [comment]
> Wait you are making manual formatting changes? I thought clang-format made that unnecessary and counter productive?!

No, I just noticed there was a redundant usage of types and an opportunity for `auto` to really improve the code. So I made a change.

> BTW I don't like the comment approach to solving the clang-format issue with #endif -- isn't there a better way?

Do you prefer this:
```cpp
#ifndef GETNAME
#define GETNAME(x) \
  case x:          \
    return #x;  // force line break
#endif
```

The problem is partly caused by the `AllowShortCaseLabelsOnASingleLine: true` flag and we can't change this to false. It would mess up way too much other code.

**Comment by harrism** [comment]
Either is fine. Seems like a bug should be filed to clang-format to always put #endif on its own line...

**Pull request merged**
