### PR TITLE
Remove padding from device_memory_resource

### LINKED ISSUE #865: [FEA] RMM should not pad allocations
**Is your feature request related to a problem? Please describe.**
Currently, RMM pads every allocation that goes through the `rmm::device_memory_resource` interface to a multiple of 8 bytes in size. 

https://github.com/rapidsai/rmm/blob/8527317aa63efe37c9815b1419c893e666cbea56/include/rmm/mr/device/device_memory_resource.hpp#L102-L105

This was originally added in #165, which doesn't provide explanation of why. I believe it was to allow accessing structures via aliases in cuIO in a way that would otherwise be UB.  

**Describe the solution you'd like**
We should not pad allocations unnecessarily. RMM allocation should not have surprising behavior like this.

### LINKED ISSUE #1156: [BUG] There is no overflow checking on alignment
**Describe the bug**
I know it feels a bit far fetched that anyone would ask to allocate 18446744073709551612 bytes (about 16 exa-bytes). But if someone does the allocation will succeed and return `nullptr` as the result. The reason for this is because there is no overflow checking in `align_up`, and `align_up` is called [for all device allocations
](https://github.com/rapidsai/rmm/blob/bf4cdb7e874eb11ba571d4762fc53ea6fd6b7051/include/rmm/mr/device/device_memory_resource.hpp#L108), so when it is aligned up and overflows the size becomes 0 bytes, which succeeds.

The problem really starts to show up when using CUDF with RMM.  CUDF uses an `int32_t` for a lot of size calculations. Because it is signed it can overflow to a negative number, and when it does it gets translated into a really large positive number. The example came from CUDF when it overflowed and tried to allocate -4 bytes when doing a string concatenation.  This resulted in the call succeeding and an error happening after the fact when we tried to use the result some other place and an assertion went off about having a negative sized length in one of the columns.

**Steps/Code to reproduce bug**
Try to allocate a buffer of 18446744073709551612 bytes. It will succeed.

**Expected behavior**
Some kind of an exception preferably a `std::bad_alloc` is thrown.

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This PR removes the `align_up` call that enforces 8B padding on all RMM device memory allocations. Padding, where needed, should be the responsibility of callers, possibly with the help of a padding adapter. It should not be enforced by rmm.

I looked at all other calls to `align_up` in the library but didn't find any others that needed removing. The other calls all seemed to be used to guarantee specific intentional alignment requirements of other memory resources or adapters. I would appreciate verification from reviewers, though.

I've labeled this PR as breaking because it could break consumers that were implicitly relying on the current padding behavior.

Resolves #865
Resolves #1156

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Comment by vyasr** [comment]
See https://github.com/rapidsai/rmm/issues/865#issuecomment-1517028971 for more of a summary on the decision here.

**Review by rongou — APPROVED** [review]

**Review by harrism — APPROVED** [review]
Do you have a plan for downstream testing before merging, @vyasr ?

**Comment by vyasr** [comment]
Thanks for the reminder Mark. I've created test PRs:
- cudf: https://github.com/rapidsai/cudf/pull/13478
- cuml: https://github.com/rapidsai/cuml/pull/5448
- cugraph: https://github.com/rapidsai/cugraph/pull/3625

**Comment by harrism** [comment]
I created an issue for cuSpatial as well. Assigning you @vyasr .

**Comment by vyasr** [comment]
Updated with a cuspatial PR.

**Comment by vyasr** [comment]
OK, we now have tests passing on all the testing PRs (cugraph's has an unrelated error blocking wheel builds). Think this is good to go now.

**Comment by ttnghia** [comment]
Sorry for jumping in late. What about padding when using arena allocator? It seems that we need to modify this too: https://github.com/rapidsai/rmm/blob/0c08dd585031f58e2a9dcfbba5608cce10c423b2/include/rmm/mr/device/arena_memory_resource.hpp#L137-L144

**Comment by jakirkham** [comment]
Could you please raise an issue?

**Comment by ttnghia** [comment]
Done.

**Pull request merged**
