### PR TITLE
Skip copy `rmm::device_buffer` when it is trivial

### PR DESCRIPTION
**Pull request by jakirkham**
Similar to PR ( https://github.com/rapidsai/rmm/pull/242 ), but at the C++ level.

Should avoid overhead and potential bugs due to copying a zero length buffer.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by jrhemstad** [comment]
Is this needed? I believe `cudaMemcpyAsync` will already appropriately handle a zero-sized copy.

**Comment by jakirkham** [comment]
At one point I was having issues with crashes on trivial copy operations. So I added a guard in Python. Thought it was prudent to extend this to C++.

**Comment by jrhemstad** [comment]
I verified that `cudaMemcpyAsync` will already succeed for a zero size copy, so this check is unnecessary.

**Comment by jakirkham** [comment]
Hmm...ok. I wonder why I was seeing bad behavior before.

Anyways feel free to close if you think it is unneeded 🙂

**Comment by jrhemstad** [comment]
The zero-size copy check may have been a red herring and hiding a more insidious issue, which is why I don't think we should add the check to the C++ level. It just unnecessarily increases code entropy.

**Pull request closed without merging**
