### PR TITLE
[REVIEW] Make .clang-format consistent with cuDF and cuGRAPH [skip ci]

### PR DESCRIPTION
**Pull request by codereport**
There a few lines in the `rmm` .clang-format that are not consistent with the `cuDF` and `cuGraph` repos. This PR is to make the files consistent. 

Note that we will probably leave `AllowShortLoopsOnASingleLine: false` and add that change to the other .clang-formats at a later date.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by codereport** [comment]
Can you remove the pyhon-codereviewer @jrhemstad or @harrism? I don't have rights to.

**Comment by harrism** [comment]
Done. Ready to merge? Please use labels and projects.

**Comment by codereport** [comment]
> Done. Ready to merge? Please use labels and projects.
@harrism Yes, ready to merge. I am not an `rmm` maintainer so I can't set any of those things.

**Pull request merged**
