### PR TITLE
[WIP] Added Doxygen configuration file

### PR DESCRIPTION
**Pull request by jrhemstad**
closes https://github.com/rapidsai/rmm/issues/45

Adds a Doxygen configuration file that allows building the HTML version of Doxygen documentation.

### CODE REVIEW

**Comment by jrhemstad** [comment]
> I think we should add a CMake target to generate the documentation.
> https://stackoverflow.com/questions/34878276/build-doxygen-from-cmake-script

I'd support that.

However, I do feel strongly that we should also have a stand-alone web-hosted version of the docs like Thrust does: https://thrust.github.io/doc/index.html

**Comment by harrism** [comment]
Of course, but we need a target in order to build those HTML docs to put on the web, right?

**Comment by harrism** [comment]
Without the target, I can't really review this PR, since I can't see the output docs.

**Comment by jrhemstad** [comment]
> Without the target, I can't really review this PR, since I can't see the output docs.

Ooo, I see what you're saying.

You can generate the html manually:

```
doxygen doxygen/Doxyfile
```

**Comment by devavret** [comment]
@harrism , I added the target. `make rmm_doc` will put the docs in doxygen/html

**Comment by jrhemstad** [comment]
Could you rename the target to `make doxygen`?

**Comment by devavret** [comment]
> Could you rename the target to `make doxygen`?

Then what happens if rmm is used as a submodule? Then there would be two targets named doxygen.

**Comment by jrhemstad** [comment]
> > Could you rename the target to `make doxygen`?
> 
> Then what happens if rmm is used as a submodule? Then there would be two targets named doxygen.

**Pull request merged**
