### PR TITLE
test west region runners and fluentbit aggregator

### PR DESCRIPTION
**Pull request by msarahan**
This is testing new infrastructure and should not be merged. Please ignore.

@ajschmidt8

### CODE REVIEW

**Comment by harrism** [comment]
Can this be moved to 25.02? Code freeze begins tomorrow.

**Comment by bdice** [comment]
@msarahan Is this safe to close now?

**Comment by msarahan** [comment]
Not quite. I'm still going to be using it to test rollout of https://github.com/rapidsai/shared-actions/pull/28, which is a further refinement of the "dispatch actions" idea and also shifts the "summarize" part to one final job, so that we don't need to worry about whether a worker for a given job other than the final one is or is not in the VPC.

**Comment by msarahan** [comment]
On second thought, I think it'll be cleaner to just open a new PR.

**Pull request closed without merging**
