### PR TITLE
[REVIEW] logging: add auto_flush to make_logging_adaptor

### PR DESCRIPTION
**Pull request by germasch**
This does duplicate the defaults, but well, I don't want to wait for C++17... This is to make the make_ helpers match the constructors.

I know it's late for 0.16, but the `make_logging_adaptors` are missing the (defaulted) `auto_flush` argument, which I happen
to need. It's a rather straightforward and small change.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by jrhemstad — APPROVED** [review]

**Comment by harrism** [comment]
We need to retarget this to 0.17.

**Comment by germasch** [comment]
It looks like the auto-merge of 0.16 PRs into 0.17 isn't working this time around -- when I merged with 0.17, this PR now picked up the code-of-conduct changes from 0.16. (no real harm done, though)

**Comment by harrism** [comment]
I don't think I understand... Code of conduct should be in 0.16,  and therefore in 0.17.

**Comment by germasch** [comment]
> I don't think I understand... Code of conduct should be in 0.16, and therefore in 0.17.

Yes, that's what I mean. It should be (should have been auto-merged, I suppose), but it's not in `branch-0.17`.

**Comment by harrism** [comment]
I see. Checking with our devops.

**Comment by germasch** [comment]
Could someone say "ok to test"? ;)

**Comment by harrism** [comment]
ok to test (sorry)

**Review by harrism — APPROVED** [review]

**Pull request merged**
