### PR TITLE
[WIP] Replace legacy RMM API usage in Cython with `memory_resource` 

### PR DESCRIPTION
**Pull request by shwina**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by jakirkham** [comment]
Thanks for starting this @shwina! 😄

**Comment by shwina** [comment]
Oops - I realized this PR's branch isn't from my fork. Apologies -- it looks like I abused my admin privileges by mistake. Closing this PR, then deleting this branch.

Opening #363 in its stead.

**Comment by cwharris** [comment]
> it looks like I abused my admin privileges by mistake

I'm confused... what was the error here?

**Comment by shwina** [comment]
The PR branch was `rapidsai/rmm:memory-resource-cython` as opposed to `shwina/rmm:memory-resource-cython`.

**Pull request closed without merging**
