### PR TITLE
Add device_async_resource_ref convenience alias

### LINKED ISSUE #1442: [FEA]  Add a convenience alias in RMM for `cuda::mr::async_resource_ref<cuda::mr::device_accessible>`
To make it easier for other libraries to use `resource_ref`s instead of `device_memory_resource` pointers, add a new header with alias for the commonly used `cuda::mr::async_resource_ref<cuda::mr::device_accessible>`.

### PR DESCRIPTION
**Pull request by harrism**
## Description
Adds a new header `include/rmm/resource_ref.hpp` that currently just contains a single `using` alias to make it easier to spell a device-accessible async_resource_ref.  

Closes #1442 

`rmm::device_async_resource_ref` is an alias for `cuda::mr::async_resource_ref<cuda::mr::device_accessible>`.

This is 30 characters vs. 57. It is shorter than the currently used resource pointer spelling: `rmm::mr::device_memory_resource*`.

Also updates tests to use this alias. 

Also makes one unrelated doc change, I noticed `pinned_host_memory_resource` was not added to a doxygen group, so I fixed that.

I was going to put this in cuDF, but @bdice [suggested maybe it would be useful to have it in RMM](https://github.com/rapidsai/cudf/pull/14873#issuecomment-1911196690).

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Want to add a test?

**Comment by jrhemstad** [comment]
> This is 34 characters vs. 57. I would like to make it shorter, but I think it would lose some information.

You could probably drop the "async" since RMM's allocation APIs have always been async and it's well understood at this point.

So `rmm::mr::device_resource_ref`.

**Review by miscco — APPROVED** [review]

**Comment by harrism** [comment]
> > This is 34 characters vs. 57. I would like to make it shorter, but I think it would lose some information.
> 
> You could probably drop the "async" since RMM's allocation APIs have always been async and it's well understood at this point.
> 
> So `rmm::mr::device_resource_ref`.
> 
> It wouldn't hurt anything to drop the `mr::` either.

RMM has always had some MRs that are synchronous (e.g. `cuda_memory_resource`). That's what `supports_streams()` was for. Also `host_memory_resource` is synchronous. The fact that nobody has used anything non-stream-ordered from RMM so far is a different fact.

If I remove `mr::`, should I also move the file up a level?

**Comment by harrism** [comment]
Answered my own question. Moved the header up a level and move up to rmm:: namespace. This is now shorter spelling than the resource pointer used by RAPIDS libraries, so it's a net win:

```
rmm::device_async_resource_ref mr; // new
rmm::mr::device_memory_resource *mr; // old
````

**Pull request merged**
