### PR TITLE
Update black version

### PR DESCRIPTION
**Pull request by vyasr**
This PR updates to black 22.3.0 which contains a critical bugfix for a recent release of Click 8.1.0. It also includes some minor reformatting associated with the version bump.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Vyas! 😄

Looks like we are getting some [failures from `black`]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Frmm%2Fprb%2Frmm-style/detail/rmm-style/2246/pipeline#log-51 ). Guessing this will be resolved by PR ( https://github.com/rapidsai/integration/pull/452 )?

**Comment by vyasr** [comment]
Yup, the version of black in the build environment won't actually be updated until the PR that you linked gets merged. Then the style checks here should pass.

**Comment by vyasr** [comment]
rerun tests

**Comment by bdice** [comment]
Is this pulling the right version of `black` for the CI checks? (Is it sourced from the integration repo or the environment yml defined in this file?) I'll rerun tests just to check. CI output:

> would reformat /workspace/python/rmm/rmm.py
> would reformat /workspace/python/rmm/tests/test_rmm.py
> Oh no! 💥 💔 💥
> 2 files would be reformatted, 11 files would be left unchanged.

**Comment by bdice** [comment]
rerun tests

**Comment by vyasr** [comment]
> Is this pulling the right version of `black` for the CI checks? (Is it sourced from the integration repo or the environment yml defined in this file?) 

This should just be using whatever's in the integration repo, which is why tests were failing yesterday. However, now images are out and tests are still failing so I'm investigating further.

> This file needs to be updated as well: https://github.com/rapidsai/rmm/blob/branch-22.06/python/dev_requirements.txt
> 
> (Or maybe we just need to remove it? The conda environment has similar specifications. Also the dev requirements can be met entirely with pip/scikit-build + pre-commit now, I think, so the extra file may not be needed.)

I'm not sure what to do with this. I believe it was originally added to support a Dockerfile that is no longer maintained within the repo. I'll just update it for now and we can address the potential cleanup in a subsequent PR.

**Comment by vyasr** [comment]
I've pulled the image locally and for some reason it's still got the wrong (old) version of black. My best guess is that the mixing of rapidsai/integration#452 and rapidsai/integration#455 caused the integration repo to upload slightly out-of-date images. I'll follow up with ops.

**Comment by vyasr** [comment]
It looks like the built images were indeed based on slightly out of date files. Once new versions are up we can run tests again.

**Comment by jakirkham** [comment]
It seems the `style` check is failing related to `black` formatting. Are we still missing an update somewhere?

**Comment by vyasr** [comment]
> It seems the `style` check is failing related to `black` formatting. Are we still missing an update somewhere?

[The Docker images haven't been updated yet](https://hub.docker.com/r/gpuci/rapidsai-driver/tags) from the ones we had last night, which were the out-of-date ones. @ajschmidt8 triggered new builds but they don't appear to have been uploaded yet.

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
So CI is pulling in the image that was built last night, but we are still seeing a failure here

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Hooray the style check passes! 🎉

**Review by jakirkham — APPROVED** [review]

**Review by Ethyling — APPROVED** [review]

**Comment by charlesbluca** [comment]
Is there anything else that needs to be done here or are we safe to merge?

**Comment by jakirkham** [comment]
@gpucibot merge

**Pull request merged**
