### PR TITLE
[WIP] Add hooks to remove cudatoolkit requirement for aarch64 architecture

### PR DESCRIPTION
**Pull request by JasonAtNvidia**
Added hooks to remove cudatoolkit requirement for aarch64 architecture as there is no Anaconda package to remote link the cudatoolkit on Jetson

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jakirkham** [comment]
Should we be removing this or should we just be working on adding a `cudatoolkit` package there?

cc @kkraus14 @mike-wendt

**Comment by kkraus14** [comment]
I think long term the plan should be to add an `aarch64` `cudatoolkit` package, but I don't know the level of effort involved in that where I don't think this is a particularly expensive workaround for the time being.

**Comment by mike-wendt** [comment]
Best timetable is mid/late next week to work on CTK for `aarch64` the hardware is connected to gpuCI, just CUDA 11 bringup is the larger priority right now. There are some missing containers for the build as well as other dependent pkgs that need to be brought up. So with that we probably shouldn't hold this up if it helps unblock from source builds/testing. Getting conda support for `aarch64` is one thing, gpuCI support won't be until v0.16. With the release extension of v0.15 you're looking at a September timeline to have PR testing for `aarch64`. To shorten the timelines my take was going to build nightlies only of `aarch64` as a gap filler.

**Comment by JasonAtNvidia** [comment]
I’ve looked at what is involved in an aarch64 cudatoolkit package and it is not easy. Especially because with CUDA 11 they have made an ARM64 build that is not compatible with Jetson.  Is there a jinja way to look for nvcc without requiring the toolkit?  It might also be easiest to make a package that does nothing but symbolic links for cuda.

**Comment by harrism** [comment]
@JasonAtNvidia note I changed the base for this PR to 0.16 -- make sure to merge branch-0.16 into your PR branch, and move the changelog entry to the 0.16 section.

**Comment by JasonAtNvidia** [comment]
I made a PR against the cudatoolkit-feedstock to add support for an aarch64 cudatoolkit, currently only available for 10.2 on L4T.  It will get more complicated with ARM64 CUDA 11 that is not compatible with Jetson.  It will make this PR void if accepted.
https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/10

**Comment by harrism** [comment]
@JasonAtNvidia shall we push this to 0.17? We are in burndown for 0.16.

**Comment by JasonAtNvidia** [comment]
What do you want to do?  rmm builds easily with the cudatoolkit I have in my Anaconda channel, but there is zero movement on actually getting it into a conda-forge package.  It would reduce Jetson memory size to not have a second cuda be required to be installed, but every RAPIDS recipe calls for it.  I don’t see great choices.

**Comment by harrism** [comment]
I am not the right person to ask, I have not looked into this PR at all.

**Comment by harrism** [comment]
To be clear, I have a lot of PRs to review, so I ignore PRs that are not marked ready for review. You also have to at least add a changelog entry for CI to run.

**Comment by harrism** [comment]
Pushing to 0.17.

**Comment by harrism** [comment]
@JasonAtNvidia can this be closed? If not, how do we move it forward?

**Comment by JasonAtNvidia** [comment]
> @JasonAtNvidia can this be closed? If not, how do we move it forward?

I've had to move on and haven't looked at RAPIDS on Jetson in months, so close it for now and a solution will have to wait until I come back around to this.

**Pull request closed without merging**
