### PR TITLE
Create labeler.yml

### PR DESCRIPTION
**Pull request by jolorunyomi**
# Summary
This PR adds a GitHub action (PR Labeler) to auto label PRs based on a labeling rule and changes in PR.

### CODE REVIEW

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
Please see the similar comment on the cuDF PR below about updating the file/path patterns.

https://github.com/rapidsai/cudf/pull/7044#discussion_r550248866

**Review by ajschmidt8 — APPROVED** [review]

**Comment by harrism** [comment]
This PR needs a description.

**Comment by raydouglass** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
@gpucibot okay to merge

**Pull request merged**
