### PR TITLE
[Improvement] Fetch runtime version with cuda-python instead of numba

### LINKED ISSUE #948: Fetch runtime version with cuda-python instead of numba.
PR #946 introduces a workaround for an issue in cuda-python that fetches a hardcoded CUDA runtime version. https://github.com/NVIDIA/cuda-python/issues/16

Once that upstream issue is resolved, we should update the implementation in RMM to use `cuda.cudart.cudaRuntimeGetVersion()` instead of `numba.cuda.runtime.get_version()`.

_Originally posted by @jakirkham in https://github.com/rapidsai/rmm/pull/946#discussion_r788126573_

### PR DESCRIPTION
**Pull request by Matt711**
## Description

Closes #948 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rmm/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

### CODE REVIEW

**Review by harrism — APPROVED** [review]
Thanks!

**Comment by Matt711** [comment]
Okay CI is failing is failing because `cuda.cudart.getLocalRuntimeVersion()` is raising a `RuntimeError` in cuda 11.8 devcontainer.
```python
In [1]: from cuda import cudart

In [2]: cudart.getLocalRuntimeVersion()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 1
----> 1 cudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/cudart.pyx:24961, in cuda.cudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/ccudart.pyx:2365, in cuda.ccudart.getLocalRuntimeVersion()

File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/_lib/ccudart/ccudart.pyx:2121, in cuda._lib.ccudart.ccudart._getLocalRuntimeVersion()

RuntimeError: Failed to dlopen libcudart.so.12
```

**Comment by Matt711** [comment]
> Okay CI is failing is failing because `cuda.cudart.getLocalRuntimeVersion()` is raising a `RuntimeError` in cuda 11.8 devcontainer.
> 
> ```python
> In [1]: from cuda import cudart
> 
> In [2]: cudart.getLocalRuntimeVersion()
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[2], line 1
> ----> 1 cudart.getLocalRuntimeVersion()
> 
> File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/cudart.pyx:24961, in cuda.cudart.getLocalRuntimeVersion()
> 
> File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/ccudart.pyx:2365, in cuda.ccudart.getLocalRuntimeVersion()
> 
> File ~/.conda/envs/rapids/lib/python3.11/site-packages/cuda/_lib/ccudart/ccudart.pyx:2121, in cuda._lib.ccudart.ccudart._getLocalRuntimeVersion()
> 
> RuntimeError: Failed to dlopen libcudart.so.12
> ```

We can merge this PR after https://github.com/NVIDIA/cuda-python/issues/89 is closed.

**Comment by harrism** [comment]
This will need to move to 25.02. But is it unblocked now that https://github.com/NVIDIA/cuda-python/issues/89 closed?

**Comment by Matt711** [comment]
> This will need to move to 25.02. But is it unblocked now that [NVIDIA/cuda-python#89](https://github.com/NVIDIA/cuda-python/issues/89) closed?

Yes, I think it also needs #1729

**Comment by wence-** [comment]
Note that I think this means that numba can now be an optional installation dependency, rather than a required one.

**Comment by Matt711** [comment]
The changes in this PR have incorporated into #1756

**Pull request closed without merging**
